[credentials]
[credentials.usernames]

[credentials.usernames.alxtrnr]
name = "Alex Turner"
password = "$2b$12$6gX0.j0inrm3NhS99Pd1vu.v9kcBdjahSujwp4IRX3TkuBT.o8qQe"
email = "alxtrnr@example.com"

[cookie]
name = "allocation_helper"
key = "cbftbbjfAH"
expiry_days = 7

[preauthorized]
emails = ["alxtrnr@example.com"]

[user_db_dict]
alxtrnr = "ward_db_alxtrnr"